print("Introduza a nota do teste 1.")
t1=float(input())
print("Introduza a nota do teste 2.")
t2= float(input())
print("Introduza a nota do teste 3.")
t3 = float(input())
medTestes=(t1+t2+t3)/3
print("Introduza as notas do exercicio 1.")
e1=float(input())
print("Introduza as notas do exercicio 2")
e2=float(input())
print("Introduza as notas do exercicio 3")
e3=float(input())
print("Introduza as notas do exercicio 4")
e4=float(input())
print("Introduza as notas do exercicio 5")
e5=float(input())
print("Introduza as notas do exercicio 6")
e6= float(input())
print("Introduza as notas do exercicio 7")
e7 = float(input())
print("Introduza as notas do exercicio 8")
e8 = float(input())
medExercicios=(e1+e2+e3+e4+e5+e6+e7+e8)/8
mediaFinal=((85/100*medTestes)+(15/100*medExercicios))
if (mediaFinal>=5):
    print("Voce foi aprovado.")
else:
    print("Voce foi reprovado.")